server:
  port: 8080
  
logging:
  level[net.talaatharb.experiments]: DEBUG

spring:
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: create-drop
    properties[hibernate.jdbc.batch_size]: 20
  datasource:
    url: jdbc:h2:file:./db/experiments;AUTO_SERVER=TRUE;
    username: sa
    password: